# Generated by Django 5.1.5 on 2025-02-10 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('hire_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grade',
            name='material',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='faculty',
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='description',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='id',
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='faculty',
            table=None,
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField(blank=True, null=True, unique=True)),
                ('study_year', models.IntegerField(blank=True, null=True)),
                ('faculty', models.ForeignKey(blank=True, db_column='faculty', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('contact_phone', models.IntegerField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.groups')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.groups')),
                ('subject', models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.subjects')),
            ],
            options={
                'unique_together': {('group', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.students')),
                ('subject', models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalMaterials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('topic_name', models.TextField(blank=True, null=True)),
                ('material_type', models.TextField(blank=True, null=True)),
                ('material_source', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.teachers'),
        ),
        migrations.DeleteModel(
            name='EducationalMaterial',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
