# Generated by Django 5.1.6 on 2025-02-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_subjects_teachers_remove_grade_material_and_more'),
    ]

    operations = [

    ]
