# Generated by Django 5.1.5 on 2025-02-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_faculty_name'),
    ]

    operations = [

    ]
