# Generated by Django 5.1.5 on 2025-02-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_faculty_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_name',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
