# Generated by Django 5.1.5 on 2025-02-11 13:32

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_faculty_faculty_name_alter_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7 (XXX) XXX-XX-XX'", regex='^\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='hire_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7 (XXX) XXX-XX-XX'", regex='^\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
