# Generated by Django 5.1.5 on 2025-02-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_students_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalmaterials',
            name='material_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='educationalmaterials',
            name='material_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='educationalmaterials',
            name='topic_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
