# Generated by Django 5.1.5 on 2025-02-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_educationalmaterials_material_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalmaterials',
            options={'verbose_name': 'Учебный материал', 'verbose_name_plural': 'Учебные материалы'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='grades',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='groupsubject',
            options={'verbose_name': 'Группа и предмет', 'verbose_name_plural': 'Группы и предметы'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
