# Generated by Django 5.1.5 on 2025-02-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_educationalmaterials_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='password',
        ),
    ]
