# Generated by Django 5.1.5 on 2025-02-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_teachers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
