# Generated by Django 5.1.5 on 2025-02-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_teachers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
